### ISSUE TITLE
Bug : Missing example

### ISSUE THREAD

**Issue by elliotwoods** [pdrozdowski/TSPLib.Net#16]
Hey!

The code feels really great
managed to feel my way around with intellisense a bit
but the lack of an example throws things off (would be good to have a file based example, and a code only based example)

especially as TravellingSalesmanProblem doesn't have a `.Solve()` method which returns a tour.

it's unclear if perhaps this library (i.e. the underlying TSPLIB) can create solutions at all, or it can only load solutions (made how?) from files.

Thanks
Elliot

**Comment by elliotwoods** [comment]
ah i see, there are no solvers here :)

**Comment by pdrozdowski** [comment]
yes, this library purpose is to provide the common set of problems on which you can test YOUR solver.

**Comment by elliotwoods** [comment]
Are you aware of any decent .NET libraries for solving TSP's?

**Comment by pdrozdowski** [comment]
Actually never used libraries, I've experimented few times with different own ideas for solutions ;) (like we all do) It ended up with conclusion that its best to kick off with something like Greedy algorithm and when it gets stalled (stops producing better result) run it again and again. Such set of results is very good input for genetic algorithm optimalisation. These gave me decent results in decent time. I've run for problems <1000 cities, otherwise you need to wait pretty long. Proposed approach was albe to find otimal for problems <100 cities. How big your TSP problem is and ho long you want to wait for a result?

**Comment by elliotwoods** [comment]
i'm mostly looking into solutions for planning routes for laser projectors in real-time
e.g. i need to navigate to 30-1000 positions ('cities'?) in X,Y optimising the ratio of time spent at each position vs time spent travelling between them

ideally need to compute this in < 1ms
is that feasible?
there might even be some trade-off between computation time vs actual travel time (since they'll be on ~same order of magnitude)

**Comment by pdrozdowski** [comment]
I'm not sure what exactly you would like to achieve, but I have concerns if TSP is really a way to go in your case. Wouldn't it be easier to work in 'scan lines' like way as old TV sets were doing (the ones with electron cannon)?
You say you have <1ms for computation... but if so how much time you need for execution of the path (for instance how much time you need to plot 1000 points including travel times)? As I think you might not need to know entire path straight away, you just need to know next few point to visit, while keeping remaining points in a sort of queue, to which you can add more, and have some route planner working in background optimizing order on queue top X items (where X is quite low like 10 or 20). That might work. For such case you don't need any sophisticated algorithm, just something fast and simple like greedy, or something like single pass optimization.
